---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-utils
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1

fargateProfiles:
  - name: fp-gitlab
    selectors:
      - namespace: gitlab
      - namespace: kube-system
      - namespace: monitoring

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager", "scheduler"]
